INSERT INTO PRODUCTO(TIPO,PRECIO) VALUES ('TASA',15);
INSERT INTO PRODUCTO(TIPO,PRECIO) VALUES ('CAMISETA',9);
INSERT INTO PRODUCTO(TIPO,PRECIO) VALUES ('ALMOHADON',8);
INSERT INTO PRODUCTO(TIPO,PRECIO) VALUES ('VASO',13);